### ISSUE TITLE
Extract-pot throws error

### ISSUE THREAD

**Issue by MichaelCereda** [mozilla/i18n-abide#93]
doing this command

./node_modules/.bin/extract-pot --locale locale .

throws this error....

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'H:\Projects\Garmin\HTMLRenderer\node_modules\i18n-abide\`find'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at H:\Projects\Garmin\HTMLRenderer\node_modules\i18n-abide\node_modules\jsxgettext\lib\cli.js:89:30
    at Array.forEach (native)
    at main (H:\Projects\Garmin\HTMLRenderer\node_modules\i18n-abide\node_modules\jsxgettext\lib\cli.js:88:11)
    at Object.<anonymous> (H:\Projects\Garmin\HTMLRenderer\node_modules\i18n-abide\node_modules\jsxgettext\lib\cli.js:95:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

i think that it's a bash script problem

**Comment by AbeOmor** [comment]
I had the same issue, look below, but I fixed it.

 ./node_modules/.bin/extract-pot --locale locale .
/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/.bin/jsxgettext  --join-existing=true  --keyword=_ -L ejs --output-dir=/ebbid_mnt/persist/cirrus/console/locale/templates/LC_MESSAGES --from-code=utf-8 --output=messages.pot `find /ebbid_mnt/persist/cirrus/console -name '*.ejs' | grep -v node_modules | grep -v .git`


fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'true'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at /ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/cli.js:73:30
    at Array.forEach (native)
    at main (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/cli.js:72:11)
    at Object.<anonymous> (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/cli.js:79:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I also think it is a bash script issue, because when I insert 
console.log(files) 
in the /i18n-abide/node_modules/jsxgettext/lib/cli.js file (the source os the issue), printed out,

[ 'true',
  '/~~CONFIDENTIAL~~/userinvite-newpassword.ejs',
  '/~~CONFIDENTIAL~~/entitlement-change.ejs',
  '/~~CONFIDENTIAL~~/inviteadmin.ejs',
  '/~~CONFIDENTIAL~~/notifyadmin.ejs',
]

For some very odd reason 'true' is the first entry in the array, when I skipped the first entry in the array, with the commands, when is changed /i18n-abide/node_modules/jsxgettext/lib/cli.js:55

From:
 var files = opts.args;

To:
 var file = opts.args;
 var files = file.slice(1,file.length);

the ./node_modules/.bin/extract-pot --locale locale .  command to exatract the pot files worked like a charm.

I would like to know why this happens and how it can be fixed in the future

**Comment by lexoyo** [comment]
Same issue here :cake:

**Comment by AbeOmor** [comment]
Did my solution fix the problem?

**Comment by lexoyo** [comment]
Yes it did thank you so much :)
Will you make a Profit soon?

**Comment by AbeOmor** [comment]
Whats is a PR? I am new to this whole github thing. Just found the bug while doing a project at work, I thought I should inform the author, but I still dont know how.

**Comment by lexoyo** [comment]
Yes you did well 
But you can also fork the repository on github,  clone it on your computer, then fix the bug,  commit locally, push to your fork and make a pull request on github. 
https://www.atlassian.com/git/tutorials/comparing-workflows

**Comment by lexoyo** [comment]
Ok, I I found the bug in the params we pass to extract-pot, and here is the fix
https://github.com/mozilla/i18n-abide/pull/97

**Comment by AbeOmor** [comment]
Whenever I run this command to extract my pot, I always run into this error, I have tried everything. Can someone please help.

./node_modules/.bin/extract-pot --locale locale .

/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:335
throw err;
^
SyntaxError: 'return' outside of function (138:0)
at raise (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:333:15)
at parseReturnStatement (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:1682:7)
at parseStatement (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:1565:26)
at parseTopLevel (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:1526:18)
at Object.exports.parse (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:48:12)
at /ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/jsxgettext.js:128:27
at Array.forEach (native)
at parse (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/jsxgettext.js:125:24)
at Object.gen as generate
at gen (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/cli.js:36:25)Whenever I run this command to extract my pot, I always run into this error, I have tried everything. Can someone please help.

./node_modules/.bin/extract-pot --locale locale .

/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:335
throw err;
^
SyntaxError: 'return' outside of function (138:0)
at raise (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:333:15)
at parseReturnStatement (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:1682:7)
at parseStatement (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:1565:26)
at parseTopLevel (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:1526:18)
at Object.exports.parse (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/node_modules/acorn/acorn.js:48:12)
at /ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/jsxgettext.js:128:27
at Array.forEach (native)
at parse (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/jsxgettext.js:125:24)
at Object.gen as generate
at gen (/ebbid_mnt/persist/cirrus/console/node_modules/i18n-abide/node_modules/jsxgettext/lib/cli.js:36:25)

**Comment by ozum** [comment]
Same issue:

Error: ENOENT, no such file or directory 'true'

**Comment by lexoyo** [comment]
Did you try to apply [my patch](https://github.com/mozilla/i18n-abide/pull/97)?

**Comment by ozum** [comment]
Thanks @lexoyo it did solve my problem. I hope it will be merged soon.

**Comment by mhaamann** [comment]
+1 solved my issue
